config/routes.rb
OMRails::Application.routes.draw do
  resources :specifics

  resources :pins

  devise_for :users

  get 'about' => 'pages#about'

  root :to => 'pages#home'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  attr_accessible :description

  validates :description, presence: true
end

app/models/specific.rb
class Specific < ActiveRecord::Base
  attr_accessible :description

  validates :description, presence: true

  belongs_to :user
  validates :user_id, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

	has_many :specifics

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def action
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
    @pin = Pin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    @pin = Pin.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(params[:pin])

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: "new" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @pin = Pin.find(params[:id])

    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = Pin.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/specifics_controller.rb
class SpecificsController < ApplicationController
  before_filter :authenticate_user!

  # GET /specifics
  # GET /specifics.json
  def index
    @specifics = current_user.specifics.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @specifics }
    end
  end

  # GET /specifics/1
  # GET /specifics/1.json
  def show
    @specific = Specific.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @specific }
    end
  end

  # GET /specifics/new
  # GET /specifics/new.json
  def new
    @specific = current_user.specifics.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @specific }
    end
  end

  # GET /specifics/1/edit
  def edit
    @specific = currentuser.specifics.find(params[:id])
  end

  # POST /specifics
  # POST /specifics.json
  def create
    @specific = current_user.specifics.new(params[:specific])

    respond_to do |format|
      if @specific.save
        format.html { redirect_to @specific, notice: 'Specific was successfully created.' }
        format.json { render json: @specific, status: :created, location: @specific }
      else
        format.html { render action: "new" }
        format.json { render json: @specific.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /specifics/1
  # PUT /specifics/1.json
  def update
    @specific = current_user.specifics.find(params[:id])

    respond_to do |format|
      if @specific.update_attributes(params[:specific])
        format.html { redirect_to @specific, notice: 'Specific was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @specific.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specifics/1
  # DELETE /specifics/1.json
  def destroy
    @specific = current_user.specifics.find(params[:id])
    @specific.destroy

    respond_to do |format|
      format.html { redirect_to specifics_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cs_cs_helper.rb
module CsCsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/specifics_helper.rb
module SpecificsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
			Right Neighborly is the brainchild of <a href="http://alexandramcdougall.net">Alexandra McDougall</a>. 
	</small>
	</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
        
        <%= link_to "Right Neighborly", root_path, class: "brand" %>
					<div class="nav-collapse">
            <ul class="nav">
              <li><%= link_to 'About Us',  about_path %></li>
            </ul>
            <ul class="nav pull-right">
            	<% if user_signed_in? %>
                        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                      <% else %>
                    <li><%= link_to "Login", new_user_session_path %></li>
                      <% end %>
            </ul>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Right Neighborly</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<div class="container">
            <% flash.each do |name, msg| %>
                <%= content_tag(:div, msg, class: "alert alert-#{name}")%>
            <% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>

	</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>
	A science nerd at heart, after working in the high-tech and creative fields, Alex decided to use her knowledge of effective communication and 3D scanning to help empower homeowners to have greater control over and understanding of home maintenance and financial concerns.  
</p>

app/views/pages/home.html.erb
<% if user_signed_in? %>
	<h1>You're logged in!<h1>
<% else %>
	<div class="hero-unit">
		<h1>Welcome to Right Neighborly!</h1>
		<p>
			We believe that home is more than just a place to live. Special thanks go to  
			<%= link_to "One Month Rails", "http://onemonthrails.com"%>, for teaching our founder how to code.
		</p>
		<p>
				<%= link_to "Sign up here, to learn how we can help your condo complex to function more like a community.", new_user_registration_path, class: "btn btn-primary btn-large" %>
		</p>
	</div>
<% end %>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <%= f.input :description, as: :text, input_html: { rows: "3" } %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
  <tr>
    <td><%= pin.description %></td>
    <td><%= link_to 'Show', pin %></td>
    <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
    <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<h1>Listing Community-Specific Content</h1>

<table class=" table table-striped">
  <thead>
    <tr>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <%= render @pins %>
  </tbody>
</table>

<br />

<%= link_to 'New Pin', new_pin_path %>

app/views/pins/new.html.erb
<h1>New Community-Specific Content</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">
			<p>
  			<%= @pin.description %>
			</p>
			<%= link_to 'Edit', edit_pin_path(@pin) %> |
			<%= link_to 'Back', pins_path %>
		</div>
	</div>
</div>

app/views/specifics/_form.html.erb
<%= simple_form_for(@specific, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <%= f.input :description, as: :text, input_html: { rows: "3" } %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/specifics/_specific.html.erb
<tr>
        <td><%= specific.description %></td>
        <td><%= link_to 'Show', specific %></td>
        <% if current_user == specific.user %>
        <td><%= link_to 'Edit', edit_specific_path(specific) %></td>
        <td><%= link_to 'Destroy', specific, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
    </tr>

app/views/specifics/edit.html.erb
<h1>Editing specific</h1>

<%= render 'form' %>

<%= link_to 'Show', @specific %> |
<%= link_to 'Back', specifics_path %>

app/views/specifics/index.html.erb
<h1>Listing Community-Specific Content</h1>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Description</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            <%= render @specifics %>
        </tbody>
    </table>

    <br />

    <%= link_to 'New Specific', new_specific_path %>

app/views/specifics/new.html.erb
<h1>New specific</h1>

<%= render 'form' %>

<%= link_to 'Back', specifics_path %>

app/views/specifics/show.html.erb
<div class="row">
    <div class="span6 offset3">
        <div class="well">
        		<p>
        			<%= @specific.description %>
      			</p>
            <p>
              <%= @specific.user.name %>
            </p>
            <% if current_user == @specific.user %>
            <%= link_to 'Edit', edit_specific_path(@specific) %> |
            <% end %>
            <%= link_to 'Back', specifics_path %>
        </div>
    </div>
</div>